### PR TITLE
Default replace capture to yes

### PR DESCRIPTION
**Pull request by pickfire**
Oh, I think default to no might be a better case is it? But pretty much for me will be yes.

### CODE REVIEW

**Comment by dalance** [comment]
Thank you for your PR.
I agree to set default behavior. But it seems to be misleading that any key without n/a/q means Yes.
I think "[Y]es/[n]o/[a]ll/[q]uit:" shows that Enter means Yes ( because 'Y' is uppercase ), and any key without y/n/a/q/Enter should show the prompt repeatedly.

**Comment by pickfire** [comment]
Yes, most of the stuff I seen on CLI app have similar behavior. @dalance One nice example is `pacman`.

**Comment by dalance** [comment]
So I think `loop` is required to repeat prompt, and `match` becomes like below?

```rust
match key {
    'Y' | 'y' | '\n' => {
        do_replace = true;
        break;
    }
    'N' | 'n' => {
        do_replace = false;
        break;
    }
    'A' | 'a' => {
        self.all_replace = true;
        break;
    }
    'Q' | 'q' => {
        let _ = tmpfile.close();
        exit(0, &mut self.console);
    }
    _ => continue,
}
```

**Comment by pickfire** [comment]
@dalance Ah, I was planning to remove the loop since assuming any key is pressed, maybe I will revert back.

**Comment by dalance** [comment]
Thanks

**Pull request merged**
